# Generated by Django 4.2.13 on 2024-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='Is student'),
        ),
    ]
